sudo: false
language: node_js
node_js: stable
install:
  - npm install
services: mongodb
script:
  - npm run test
after_success:
  - npm run coverage
before_script:
  - sleep 15
  - mongo challengeTest --eval 'db.createUser({user:"challengeUser",pwd:"challenge2020",roles:["readWrite"]});'
